title: Logistics BPO Blog
description: Insights on Logistics Outsourcing, Freight Audit & Back Office

# REQUIRED FOR PROJECT SITES
baseurl: "/logisticsBPO"
url: "https://backofficeoutsource.github.io"

paginate: 5
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  posts:
    output: true

author:
  name: Logistics BPO
  email: info@example.com

permalink: /:year/:month/:day/:title/

