title: Logistics BPO Blog
description: Insights on Logistics Outsourcing, Freight Audit & Back Office
theme: minima
paginate: 5

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

author:
  name: Logistics BPO
  email: info@example.com

# Optional but nice
permalink: /:categories/:title/

