title: Logistics BPO Blog
description: Insights on Logistics Outsourcing, Freight Audit & Back Office

paginate: 5

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

author:
  name: Logistics BPO
  email: info@example.com

permalink: /:categories/:title/
